### ISSUE TITLE
Exception during indexing

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#4353]
```
TypeError: (e[p] ?? []) is not iterable
    at ZD (/usr/src/app/bundle.js:50:4595)
    at wde.collect (/usr/src/app/bundle.js:50:3137)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/bundle.js:8:12006
    at async W_.with (/usr/src/app/bundle.js:7:1572)
    at async m1e.processIndex (/usr/src/app/bundle.js:8:11940)
    at async /usr/src/app/bundle.js:8:9901
    at async W_.with (/usr/src/app/bundle.js:7:1572)
    at async Lle.exec (/usr/src/app/bundle.js:3:23900)
    at async m1e.doIndexing (/usr/src/app/bundle.js:8:9838)
TypeError: (e[p] ?? []) is not iterable
    at ZD (/usr/src/app/bundle.js:50:4595)
    at wde.collect (/usr/src/app/bundle.js:50:3137)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/bundle.js:8:12006
    at async W_.with (/usr/src/app/bundle.js:7:1572)
    at async m1e.processIndex (/usr/src/app/bundle.js:8:11940)
    at async /usr/src/app/bundle.js:8:9901
    at async W_.with (/usr/src/app/bundle.js:7:1572)
    at async Lle.exec (/usr/src/app/bundle.js:3:23900)
    at async m1e.doIndexing (/usr/src/app/bundle.js:8:9838)
```

**Comment by ThetaDR** [comment]
fulltextPush.ts:313:103
(doc[docIdAttr] ?? []) is not iterable
