### ISSUE TITLE
Can setup empty status for the issue

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#4561]
**Summary**

Can setup an empty status for the issue

**Steps to reproduce:**

1. Login to platform
2. Create an issue
3. Open new issue
4. Press on the Status field
5. Press Tab button
6. Click outside of the status selector

**Actual Result**

Status is empty

**Expected Result**

Status should not changed

```
8785.fb15c5b7ee3df5ed1427.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '$lookup')
    at 8785.fb15c5b7ee3df5ed1427.js:1:258330
    at Array.map (<anonymous>)
    at e.$$.update (8785.fb15c5b7ee3df5ed1427.js:1:258272)
    at Ze (bundle.a85c2925adbb773840e6.js:2:2536166)
    at Ve (bundle.a85c2925adbb773840e6.js:2:2535881)
```

**Comment by haiodo** [comment]
[Bykhov Denis](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d983ba125a3831a3424ff&label=Bykhov%20Denis) Hi, could you take a look, could it be same query related?
