### ISSUE TITLE
Failed to add the table to the issue description

### ISSUE THREAD

**Issue by aonnikov** [hcengineering/platform#4712]
**Summary**

Failed to add the table to the issue description

**Steps to reproduce:**

1. Login to platform
2. Created an issue
3. Try to add any table

**Actual Result**

Error TypeError: Cannot read properties of undefined (reading 'element') occurs

Example: <https://front.hc.engineering/workbench/platform/tracker/TESTS-198>

**Expected Result**

The table should be added

```
bundle.6cfabe35963be1a2e12a.js:29 Uncaught TypeError: Cannot read properties of undefined (reading 'element')
    at get dom (bundle.6cfabe35963be1a2e12a.js:29:30634)
    at Je.create (bundle.6cfabe35963be1a2e12a.js:205:3927)
    at pr.addNode (bundle.6cfabe35963be1a2e12a.js:205:15419)
    at bundle.6cfabe35963be1a2e12a.js:205:5840
    at Wr (bundle.6cfabe35963be1a2e12a.js:205:17248)
    at Je.updateChildren (bundle.6cfabe35963be1a2e12a.js:205:5358)
    at Je.updateInner (bundle.6cfabe35963be1a2e12a.js:205:7150)
    at Je.update (bundle.6cfabe35963be1a2e12a.js:205:7021)
    at Va.updateStateInner (bundle.6cfabe35963be1a2e12a.js:208:45188)
    at Va.updateState (bundle.6cfabe35963be1a2e12a.js:208:44200)
```

**Comment by aonnikov** [comment]
Already fixed in [UBER-1217](https://front.hc.engineering/browse/?workspace=platform&_class=tracker%3Aclass%3AIssue&_id=65d08ae80b8a4818a5ee8657&label=UBER-1217)
