### ISSUE TITLE
Failed to save the issue description

### ISSUE THREAD

**Issue by aonnikov** [hcengineering/platform#4713]
**Summary**

Failed to save the issue description

Example of issue: <https://front.hc.engineering/workbench/platform/tracker/TESTS-184>

**Steps to reproduce:**

1. Login to platform
2. Created an issue
3. Try to add any table
4. Close the issue and open it again
5. Try to add any description
6. Close the issue and open it again

**Actual Result**

The description is missed, but the activity with the change description is added to the ticket

The Uncaught (in promise) Error: Issue project not found, _id: 65d3c12247f20a8c62116901 error occurs

```
8349.96fee57b4de8caa5c878.js:1 Uncaught (in promise) Error: Issue project not found, _id: 65d3c12247f20a8c62116901
    at ui (8349.96fee57b4de8caa5c878.js:1:18217)
    at async bn (view.2a2b9bdf80c25febd0a8.js:5:6888)
    at async nl (view.2a2b9bdf80c25febd0a8.js:5:6973)
    at async Qe (activity.3621f7cb830db963a28d.js:1:22934)
```

**Expected Result**

The description should be saved

**Comment by aonnikov** [comment]
This ie probably related to the same problem as in [UBER-1217](https://front.hc.engineering/browse/?workspace=bb793ec1-252e-4419-8998-7f220ababdfa&_class=tracker%3Aclass%3AIssue&_id=65d08ae80b8a4818a5ee8657&label=UBER-1217) , [Vyacheslav Tumanov](https://front.hc.engineering/browse/?workspace=bb793ec1-252e-4419-8998-7f220ababdfa&_class=contact%3Aclass%3APerson&_id=63bbaa4f93f7b75720ef0f0e&label=Vyacheslav%20Tumanov) could you please check?
