### ISSUE TITLE
upgrade exception

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#4877]
```
---UPGRADING---- w-huly-hoang-65dadcba-8ec61fb9c1-c7d8f2 logs/w-huly-hoang-65dadcba-8ec61fb9c1-c7d8f2.log
upgrade from "0.6.207" to "0.6.208"
ERROR request: tx response-id: 6 error:  {
  severity: 'ERROR',
  code: 'platform:status:UnknownError',
  params: {
    message: 'E11000 duplicate key error collection: w-huly-hoang-65dadcba-8ec61fb9c1-c7d8f2.space index: _id_ dup key: { _id: "chunter:space:Random" }'
  }
} result:  MongoServerError: E11000 duplicate key error collection: w-huly-hoang-65dadcba-8ec61fb9c1-c7d8f2.space index: _id_ dup key: { _id: "chunter:space:Random" }
    at aH.execute (/usr/src/app/bundle.js:174:62332)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async uLn (/usr/src/app/bundle.js:174:50900)
    at async Object.raw (/usr/src/app/bundle.js:191:200318)
    at async Rme.tx (/usr/src/app/bundle.js:191:198655)
    at async /usr/src/app/bundle.js:50:10566
    at async t.with (/usr/src/app/bundle.js:7:2523)
    at async processPart (/usr/src/app/bundle.js:50:10520)
    at async Aie.routeTx (/usr/src/app/bundle.js:50:10968)
    at async t.with (/usr/src/app/bundle.js:7:2523)
```

**Comment by haiodo** [comment]
```
upgrade from "0.6.207" to "0.6.208"
ERROR request: tx response-id: 6 error:  {
  severity: 'ERROR',
  code: 'platform:status:UnknownError',
  params: {
    message: 'E11000 duplicate key error collection: w-tjk1dol3-test-65daffd0-0e9f63a305-2e5f4a.space index: _id_ dup key: { _id: "chunter:space:Random" }'
  }
} result:  MongoServerError: E11000 duplicate key error collection: w-tjk1dol3-test-65daffd0-0e9f63a305-2e5f4a.space index: _id_ dup key: { _id: "chunter:space:Random" }
    at aH.execute (/usr/src/app/bundle.js:174:62332)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async uLn (/usr/src/app/bundle.js:174:50900)
    at async Object.raw (/usr/src/app/bundle.js:191:200318)
    at async Rme.tx (/usr/src/app/bundle.js:191:198655)
    at async /usr/src/app/bundle.js:50:10566
    at async t.with (/usr/src/app/bundle.js:7:2523)
    at async processPart (/usr/src/app/bundle.js:50:10520)
    at async Aie.routeTx (/usr/src/app/bundle.js:50:10968)
    at async t.with (/usr/src/app/bundle.js:7:2523)
```

**Comment by kristina-fefelova** [comment]
has not been reproduced in a long time, let's re-open with new details if it happens again
