### ISSUE TITLE
Exceptions during indexing

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#5103]
```
2024-03-31 00:34:36 Error: descendants not found: chunter:class:Comment
2024-03-31 00:34:36     at t.getDescendants (/usr/src/app/bundle.js:3:125140)
2024-03-31 00:34:36     at traverseFullTextContexts (/usr/src/app/bundle.js:7:20033)
2024-03-31 00:34:36     at collectPropagate (/usr/src/app/bundle.js:7:20452)
2024-03-31 00:34:36     at vse.collect (/usr/src/app/bundle.js:50:2969)
2024-03-31 00:34:36     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-31 00:34:36     at async /usr/src/app/bundle.js:8:12991
2024-03-31 00:34:36     at async t.with (/usr/src/app/bundle.js:7:2523)
2024-03-31 00:34:36     at async /usr/src/app/bundle.js:8:12944
2024-03-31 00:34:36     at async cre.exec (/usr/src/app/bundle.js:3:109957)
2024-03-31 00:34:36     at async cie.processIndex (/usr/src/app/bundle.js:8:11745)
```

 We need to be sure this will not have any influence on entire indexing process.

**Comment by ThetaDR** [comment]
[Andrey Sobolev](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d8b615bdc96430ced15a0&label=Andrey%20Sobolev) it tries to use old comment class that doesn’t exist in our model anymore. Gonna prepare a fix to clear old DocIndexState with classes that got removed/renamed, it should help.
