### ISSUE TITLE
Exception during issue creation

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#5105]
```
ERROR"request:""findAll""response-id:"273"error: " 
Object
"result: "
"TypeError: S._class.some is not a function
    at kre.findAll (/usr/src/app/bundle.js:7:27342)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.with (/usr/src/app/bundle.js:7:2523)
    at async cse.findAll (/usr/src/app/bundle.js:50:38268)
    at async t.provideFindAll (/usr/src/app/bundle.js:117:6129)
    at async t.findAll (/usr/src/app/bundle.js:117:16703)
    at async t.provideFindAll (/usr/src/app/bundle.js:117:6096)
    at async t.findAll (/usr/src/app/bundle.js:117:8082)
    at async t.provideFindAll (/usr/src/app/bundle.js:117:6096)
    at async t.findAll (/usr/src/app/bundle.js:117:5711)"
```

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjA4NTA5YTlmYTE1ODMyNDcyOWZiNDIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.Y7aF1fR-QPsRZg4laQN8WQzbQP_XHTbMIYMd4zz_AxE">Huly&reg;: <b>UBERF-6229</b></a></sub>

**Comment by BykhovDenis** [comment]
[Andrey Sobolev](https://front.hc.engineering/browse/?workspace=platform&_class=contact%3Aclass%3APerson&_id=629d8b615bdc96430ced15a0&label=Andrey%20Sobolev) It works fine and not reproduced. Any additional info?
