### ISSUE TITLE
Sentry: $in predicate requires array

### ISSUE THREAD

**Issue by aonnikov** [hcengineering/platform#5359]
<https://hardcoreeng.sentry.io/issues/5196266559/?referrer=alert_email&alert_type=email&alert_timestamp=1713141414598&alert_rule_id=14994430&notification_uuid=b2aa4e6e-6275-491b-afde-72de9c1c3b03&environment=production>

```
Error: $in predicate requires array   at predicates.$in (webpack://@uberflow/prod/../../anticrm/packages/core/src/predicate.ts:42:17)   at createPredicates (webpack://@uberflow/prod/../../anticrm/packages/core/src/predicate.ts:123:17)   at findProperty (webpack://@uberflow/prod/../../anticrm/packages/core/src/query.ts:14:19)   at matchQuery (webpack://@uberflow/prod/../../anticrm/packages/core/src/query.ts:166:14)   at ae.findAll (webpack://@uberflow/prod/../../anticrm/packages/core/src/memdb.ts:157:14) ... (10 additional frame(s) were not displayed)
```

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjFjZDRiN2ZiMTljMDhlYWJhZDgzY2UiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.96RTMUWm0HgrFKHetgiXDx3a2_bN5auF_5mQubDbgCY">Huly&reg;: <b>UBERF-6555</b></a></sub>

**Comment by praveen-erramilli** [comment]
Please assign to me
