### ISSUE TITLE
Exception in activity on transactor

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#5759]
```
err: Error: The intl string context variable "title" was not provided to the string "{title}"
      at e [as constructor] (/usr/src/app/bundle.js:1:53158)
      at new e (/usr/src/app/bundle.js:1:53886)
      at wte (/usr/src/app/bundle.js:1:54965)
      at t.formatToParts (/usr/src/app/bundle.js:3:2202)
      at t.format (/usr/src/app/bundle.js:3:1907)
      at translate (/usr/src/app/bundle.js:3:8004)
      at activityInboxNotificationToText (/usr/src/app/bundle.js:50593:19958)
      at createPushFromInbox (/usr/src/app/bundle.js:50593:21227)
      at pushInboxNotifications (/usr/src/app/bundle.js:50593:19581)
      at async pushActivityInboxNotifications (/usr/src/app/bundle.js:50593:23492) {
    code: 'MISSING_VALUE',
    originalMessage: '{title}'
  },
  level: 'error',
  timestamp: '2024-06-07T17:33:19.076Z'
}
```

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjY1YzY3YjQ1ZjAzNzUxMGNjYzA2NGYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIiwicHJvZHVjdElkIjoiIn0.JrP2WTiQhEEI8XQoYhdpgwggLLP7SNzuEZsdrhYtiCg">Huly&reg;: <b>UBERF-7196</b></a></sub>

**Comment by kristina-fefelova** [comment]
not reproducing now, let's open it again with new details if it appears
