### ISSUE TITLE
'configure' command fails with fetch error

### ISSUE THREAD

**Issue by snorkysnark** [hcengineering/platform#6443]
### Description of the issue
I get the folliwing error when running command, `rushx run-local configure ws1 --list --enable '*'`
```js
{
  severity: 'ERROR',
  code: 'platform:status:UnknownError',
  params: { message: 'fetch failed' }
}
```

### Your environment
* Version of huly: as of commit 68608dc
* Arch Linux 6.6.47-1-lts
* Node.js v20.11.0

### Steps to reproduce
Run setup in a clean environment up to  `rushx run-local configure ws1 --list --enable '*'`

**Comment by snorkysnark** [comment]
Found the full error at the transactor's side:
```
TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TSessionManager.getWorkspaceInfo (/usr/src/app/bundle.js:227532:35)
    at async TSessionManager.addSession (/usr/src/app/bundle.js:227559:48)
    at async /usr/src/app/bundle.js:15380:29 {
  [cause]: Error: getaddrinfo ENOTFOUND host.docker.internal
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'host.docker.internal'
  }
}
```
Downgrading to before eaa23c7, where `host.docker.internal` got introduced, fixes this for me
