### ISSUE TITLE
Github exception in service

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#6504]
```
{"level":"error","message":"Unhandled Rejection at:","promise":{},"reason":{"$fault":"client","$metadata":{"attempts":1,"httpStatusCode":400,"totalRetryDelay":0},"Code":"XAmzContentSHA256Mismatch","message":"The provided 'x-amz-content-sha256' header does not match what was computed.","name":"XAmzContentSHA256Mismatch","stack":"XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed.\n    at throwDefaultError (/usr/src/app/bundle.js:201807:24)\n    at /usr/src/app/bundle.js:201816:9\n    at de_CommandError (/usr/src/app/bundle.js:223843:18)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /usr/src/app/bundle.js:206562:24\n    at async /usr/src/app/bundle.js:203719:22\n    at async /usr/src/app/bundle.js:205978:42\n    at async /usr/src/app/bundle.js:218860:22\n    at async /usr/src/app/bundle.js:202951:24\n    at async /usr/src/app/bundle.js:202972:18"},"timestamp":"2024-09-09T16:43:31.703Z"}
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed.
    at throwDefaultError (/usr/src/app/bundle.js:201807:24)
    at /usr/src/app/bundle.js:201816:9
    at de_CommandError (/usr/src/app/bundle.js:223843:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/bundle.js:206562:24
    at async /usr/src/app/bundle.js:203719:22
    at async /usr/src/app/bundle.js:205978:42
    at async /usr/src/app/bundle.js:218860:22
    at async /usr/src/app/bundle.js:202951:24
    at async /usr/src/app/bundle.js:202972:18
```

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmRmMjYwY2UxNzVjYmM2NmQzYTlkMjEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.cVb778eB1yoci0BcpTtZByzQyz_iakziMkSTT2tEn8g">Huly&reg;: <b>UBERF-8054</b></a></sub>

**Comment by haiodo** [comment]
Related to patch content passed to S3 API has different lenght after upload.
