### ISSUE TITLE
Pull request are not created by integeration

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#6526]
PR are not created because patch could not be uploaded issue.

```
{"err":{"$fault":"client","$metadata":{"attempts":1,"httpStatusCode":400,"totalRetryDelay":0},"Code":"XAmzContentSHA256Mismatch","message":"The provided 'x-amz-content-sha256' header does not match what was computed.","name":"XAmzContentSHA256Mismatch","stack":"XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed.\n    at throwDefaultError (/usr/src/app/bundle.js:199933:24)\n    at /usr/src/app/bundle.js:199942:9\n    at de_CommandError (/usr/src/app/bundle.js:221969:18)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /usr/src/app/bundle.js:204688:24\n    at async /usr/src/app/bundle.js:201845:22\n    at async /usr/src/app/bundle.js:204104:42\n    at async /usr/src/app/bundle.js:216986:22\n    at async /usr/src/app/bundle.js:201077:24\n    at async /usr/src/app/bundle.js:201098:18"},"level":"error","message":"Error","timestamp":"2024-09-11T07:50:40.983Z"}
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed.
    at throwDefaultError (/usr/src/app/bundle.js:199933:24)
    at /usr/src/app/bundle.js:199942:9
    at de_CommandError (/usr/src/app/bundle.js:221969:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/bundle.js:204688:24
    at async /usr/src/app/bundle.js:201845:22
    at async /usr/src/app/bundle.js:204104:42
    at async /usr/src/app/bundle.js:216986:22
    at async /usr/src/app/bundle.js:201077:24
    at async /usr/src/app/bundle.js:201098:18
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed.
    at throwDefaultError (/usr/src/app/bundle.js:199933:24)
    at /usr/src/app/bundle.js:199942:9
    at de_CommandError (/usr/src/app/bundle.js:221969:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/bundle.js:204688:24
    at async /usr/src/app/bundle.js:201845:22
```

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmUxNGRkZTU3NmVmNDVmNWU2ZWY5MzAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.ahOIUFDXzEKnDPXbCAqhu7-KXxXFyEmtIZVraeREYPw">Huly&reg;: <b>UBERF-8072</b></a></sub>

**Comment by haiodo** [comment]
{"action":"opened","level":"info","login":"haiodo","message":"issue:handleEvent","nodeId":"<https://github.com/hcengineering/platform/issues/6526","timestamp":"2024-09-11T07:59:28.979Z","type":"User","url":"https://api.github.com/users/haiodo","workspace":"platform>"}
