### ISSUE TITLE
Check space security unhandled rejection

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#6706]
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ERROR: platform:status:Forbidden {}
    at _SpacePermissionsMiddleware.throwForbidden (/usr/src/app/bundle.js:323072:15)
    at _SpacePermissionsMiddleware.checkPermissions (/usr/src/app/bundle.js:323237:18)
    at _SpacePermissionsMiddleware.tx (/usr/src/app/bundle.js:323208:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _SpaceSecurityMiddleware.tx (/usr/src/app/bundle.js:323641:16)
    at async _PipelineImpl.tx (/usr/src/app/bundle.js:73099:18)
    at async ClientSession2.tx (/usr/src/app/bundle.js:225911:24)
Unhandled Rejection at: Promise {
  <rejected> PlatformError: ERROR: platform:status:Forbidden {}
      at _SpacePermissionsMiddleware.throwForbidden (/usr/src/app/bundle.js:323072:15)
      at _SpacePermissionsMiddleware.checkPermissions (/usr/src/app/bundle.js:323237:18)
      at _SpacePermissionsMiddleware.tx (/usr/src/app/bundle.js:323208:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async _SpaceSecurityMiddleware.tx (/usr/src/app/bundle.js:323641:16)
      at async _PipelineImpl.tx (/usr/src/app/bundle.js:73099:18)
      at async ClientSession2.tx (/usr/src/app/bundle.js:225911:24) {
    status: Status {
      severity: 'ERROR',
      code: 'platform:status:Forbidden',
      params: {}
    }
  }
} reason: PlatformError: ERROR: platform:status:Forbidden {}
    at _SpacePermissionsMiddleware.throwForbidden (/usr/src/app/bundle.js:323072:15)
    at _SpacePermissionsMiddleware.checkPermissions (/usr/src/app/bundle.js:323237:18)
    at _SpacePermissionsMiddleware.tx (/usr/src/app/bundle.js:323208:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _SpaceSecurityMiddleware.tx (/usr/src/app/bundle.js:323641:16)
    at async _PipelineImpl.tx (/usr/src/app/bundle.js:73099:18)
    at async ClientSession2.tx (/usr/src/app/bundle.js:225911:24) {
  status: Status {
    severity: 'ERROR',
    code: 'platform:status:Forbidden',
    params: {}
  }
}
```

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmYyYTAwZGIzODE1OGE2NWEyZWU0NjUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.H-vTZk7RbgN-aUn-V49cT2aKFyLLbD4yi6xpnu0tMcQ">Huly&reg;: <b>UBERF-8254</b></a></sub>

**Comment by lexiv0re** [comment]
What’s the context of this exception? It originates from the permissions control on the server side and someone tried to perform a transaction that is forbidden based on his roles. If it’s not an automation/tool call then UI should have prevented this transaction from happening in the first place.

**Comment by haiodo** [comment]
Question only for Unhandled Rejection
