### ISSUE TITLE
Getting an error while creating an workspace.

### ISSUE THREAD

**Issue by ChandanTeekinavar** [hcengineering/platform#6800]
Followed below procedures.

* I took reference from the kubernetes manifest files which is in the following https://github.com/hcengineering/huly-selfhost/tree/main/kube
* I have created the polymorphic-app helm-chart which is in the following link https://artifacthub.io/packages/helm/improwised/polymorphic-app
  by taking reference from the kuberenetes manifest files which is in the huly-selfhost repo.
* I am deploying the application through FluxCD.
* The below is the github repo link where the the HelmRelease file is located.
  https://github.com/ChandanTeekinavar/imp-flux/tree/main/musketeers-3/huly
* The application pod is running. I can able to signup or login.
* But while creating a workspace I am getting an error. The workspace will be in creating state.
* In the worksapce pod I am getting below error.
  {"level":"error","message":"Unhandled Rejection at:","promise":{},"reason":{"message":"fetch failed","stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:13178:13\n  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async workerHandshake (/usr/src/app/bundle.js:253:440289)\n    at async bRt.start (/usr/src/app/bundle.js:460:150449)"},"timestamp":"2024-10-03T14:06:03.096Z"}
* Below is the account pod log.
  {"level":"info","message":"getPendingWorkspace","mode":"creating","operation":"all","region":"","timestamp":"2024-10-03T13:34:28.675Z","version":{"major":0,"minor":6,"patch":315},"worksp │
  │ aceId":"w-chandanteeki-admin-66fe9888-593e857bd8-82407f","workspaceName":"admin"}                                                                                                          │
  │ {"event":"create-done","level":"info","message":"update workspace info: create-done","progress":100,"timestamp":"2024-10-03T13:34:28.686Z","version":{"major":0,"minor":6,"patch":315},"wo │
  │ rkspaceId":"w-chandanteeki-admin-66fe9888-593e857bd8-82407f"}
* I am not getting the below
  https://github.com/hcengineering/platform/blob/4234931d82709c9fe53c35a2af75475f91aea014/server/account/src/operations.ts#L1203

<sub><a href="https://front.hc.engineering/guest/platform?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZlYTg3MmU3OTVmNWE2MjkzZjRhODQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InBsYXRmb3JtIn0.X3_EqHaMxfuXNEs4ayyYTRAByuTWJ7cWUDAm9eCmrsQ">Huly&reg;: <b>UBERF-8348</b></a></sub>

**Comment by lexiv0re** [comment]
@ChandanTeekinavar please try to use `v0.6.295` (latest suggested for self-hosting) or `v0.6.313` (latest release). 
`v0.6.315` tag is not a release version and it requires some configuration adjustments which haven't been published to huly-selfhost yet.
Another issue that I see is that your workspace service started before the account service and the handshake failed. There was an issue with this situation that workspace service does not retry the handshake and becomes not operational. As a workaround you should try restarting the workspace service manually in this case. The issue has been already fixed but the fix hasn't been released yet.

**Comment by ChandanTeekinavar** [comment]
![Screenshot from 2024-10-04 15-25-49](https://github.com/user-attachments/assets/d1b3ed5f-1374-4777-a1a2-85985142502e)
I have tried as suggested.
- Changed the image tag form latest to v0.6.295 in the workspace service.
- I have seperated the workspace service from other service and created a seprate HelmRelease file for workspace service. And applied the other service first and then applied workspace pod. But it did not work.
- I have changed the Image tag of all service (account, collaborator, front, rekoni, transactor) to v0.6.295 from latest and applied. But I got same error as below.
- Below is the link for HelmRelease file which include account, collaborator, front, rekoni, transactor, elasticsearch, minio, mongodb
https://github.com/ChandanTeekinavar/imp-flux/blob/main/musketeers-3/huly/helmrelease.yml
- Below is the link for worspace HelmRelease file
https://github.com/ChandanTeekinavar/imp-flux/blob/main/musketeers-3/huly/workspace-helmrelease.yml

- Below is the log of workspace pod

Logging also into console development true
{"level":"info","message":"####################################################################################################################","timestamp":"2024-10-04T07:56:38.309Z"}
{"level":"info","message":"########################SplitLogger workspace initialized: 2024-10-04T07:56:38.310Z###########################","timestamp":"2024-10-04T07:56:38.310Z"}
Starting workspace service in region: DEFAULT for operation: all for version: 0.6.294 with brandings: {}
{"level":"error","message":"Unhandled Rejection at:","promise":{},"reason":{"message":"fetch failed","stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:13178:13\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async workerHandshake (/usr/src/app/bundle.js:252:440749)\n    at async lZt.start (/usr/src/app/bundle.js:628:140641)"},"timestamp":"2024-10-04T07:56:38.375Z"}

**Comment by lexiv0re** [comment]
@ChandanTeekinavar if you see this error starting the workspace pod when the account pod is ready and running w/o errors it means there's no connectivity from the workspace pod to the account service.
In your case please make sure you can reach "http://account.huly.example/" (set in `ACCOUNTS_URL` env) from within the workspace pod.

**Comment by ChandanTeekinavar** [comment]
- As you said I checked the "http://account.huly.example/" can reachable from the workspace pod. It was giving as hostname cannot be resolved.
- So I changed the account url env in the workspace pod, istead of ingress hostname I used service name (http://huly-account-svc) as it was in the kubernetes manifest file.
- Now the from workspace pod "http://huly-account-svc" is accessible. 
- When I tried to create a workspace after making changes, The workspace is still not creating.
- I checked the logs of account pod and workspace pod there is no errors in either of them.
- But still workspace is not creating
- Below is the link for HelmRelease file which include account, collaborator, front, rekoni, transactor, elasticsearch, minio, mongodb
https://github.com/ChandanTeekinavar/imp-flux/blob/main/musketeers-3/huly/helmrelease.yml
- Below is the link for worspace HelmRelease file
https://github.com/ChandanTeekinavar/imp-flux/blob/main/musketeers-3/huly/workspace-helmrelease.yml
